### PR TITLE
Adapt to deprecation of spurt in upstream Mojolicious

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/135632

### CODE REVIEW

**Review by baierjan — APPROVED** [review]

**Review by Martchus — COMMENTED** [review]
Shouldn't the version requirement be stated in https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/blob/master/cpanfile?

**Comment by okurz** [comment]
> Shouldn't the version requirement be stated in https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/blob/master/cpanfile?

done

**Review by Martchus — APPROVED** [review]

**Comment by perlpunk** [comment]
See #52 for the perltidy workflow fix

**Comment by okurz** [comment]
https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/pull/52 merged, rebased

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
@foursixnine can you make a release soon?

**Comment by okurz** [comment]
I called `minil release` and that created additional changes including a git tag that was published here. It also said that it would upload to CPAN but I don't know where this ended up:

```
Wrote Mojo-IOLoop-ReadWriteProcess-0.34.tar.gz
Upload to CPAN
Release to CPAN ? [y/n]   y
registering upload with PAUSE web server
POSTing upload for /home/okurz/local/Mojo-IOLoop-ReadWriteProcess/.build/3LagEnuz/Mojo-IOLoop-ReadWriteProcess-0.34.tar.gz to https://pause.perl.org/pause/authenquery?ACTION=add_uri
PAUSE add message sent ok [200]
Name: Mojo::IOLoop::ReadWriteProcess
Abstract: Execute external programs or internal code blocks as separate process.
Version: 0.34
[Mojo-IOLoop-ReadWriteProcess] $ git commit -a -m Checking in changes prior to tagging of version 0.34.

Changelog diff is:

diff --git a/Changes b/Changes
index b2261f6..5f4e9d4 100644
--- a/Changes
+++ b/Changes
@@ -1,8 +1,16 @@
 
 Revision history for Perl extension Mojo-IOLoop-ReadWriteProcess
 
+0.34 2023-09-14T19:30:00Z
 {{$NEXT}}
 
+0.34 2023-09-14T19:55:18Z
+ - Adapt to deprecation of spurt in upstream Mojolicious
+ - Make git work in github workflow
+ - Turn warnings "Sleeping inside locked section" into notes
+ - Avoid warnings about using undefined value as file handle
+
+
 0.33 2022-12-12T12:22:13Z
  - Apply perltidy v20221112
  - remove hard-coding of OABI syscall entry point
 --cleanup=verbatim
[fix/spew 8544fd1] Checking in changes prior to tagging of version 0.34.
 4 files changed, 16 insertions(+), 7 deletions(-)
Pushing to origin
[Mojo-IOLoop-ReadWriteProcess] $ git push origin fix/spew
Enumerating objects: 58, done.
Counting objects: 100% (58/58), done.
Delta compression using up to 8 threads
Compressing objects: 100% (33/33), done.
Writing objects: 100% (40/40), 5.32 KiB | 1.33 MiB/s, done.
Total 40 (delta 22), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (22/22), completed with 13 local objects.
remote: 
remote: Create a pull request for 'fix/spew' on GitHub by visiting:
remote:      https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess/pull/new/fix/spew
remote: 
To github.com:openSUSE/Mojo-IOLoop-ReadWriteProcess.git
 * [new branch]      fix/spew -> fix/spew
[Mojo-IOLoop-ReadWriteProcess] $ git tag 0.34
[Mojo-IOLoop-ReadWriteProcess] $ git push origin tag 0.34
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:openSUSE/Mojo-IOLoop-ReadWriteProcess.git
 * [new tag]         0.34 -> 0.34
```

**Comment by foursixnine** [comment]
> @foursixnine can you make a release soon?

Yes, I wasn't aware of this, I'll release soon

**Comment by foursixnine** [comment]
So, I should have checked earlier and released 0.35:

image

https://metacpan.org/release/SZARATE/Mojo-IOLoop-ReadWriteProcess-0.34 is already there, I guess it'll take a bit before it ends up as the latest)

**Pull request merged**
